// <auto-generated />
using System;
using GymTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTrack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymTrack.Models.Ejercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjercicioId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dificultad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EjercicioId");

                    b.ToTable("Ejercicios");

                    b.HasData(
                        new
                        {
                            EjercicioId = 1,
                            Descripcion = "Ejercicio compuesto para pecho",
                            Dificultad = "Intermedio",
                            GrupoMuscular = "Pecho",
                            Nombre = "Press de Banca"
                        },
                        new
                        {
                            EjercicioId = 2,
                            Descripcion = "El rey de los ejercicios de pierna",
                            Dificultad = "Intermedio",
                            GrupoMuscular = "Pierna",
                            Nombre = "Sentadilla Libre"
                        },
                        new
                        {
                            EjercicioId = 3,
                            Descripcion = "Ejercicio de peso corporal para espalda",
                            Dificultad = "Avanzado",
                            GrupoMuscular = "Espalda",
                            Nombre = "Dominadas"
                        },
                        new
                        {
                            EjercicioId = 4,
                            Descripcion = "Aislamiento para bíceps",
                            Dificultad = "Básico",
                            GrupoMuscular = "Brazos",
                            Nombre = "Curl de Bíceps"
                        },
                        new
                        {
                            EjercicioId = 5,
                            Descripcion = "Empuje vertical para hombros",
                            Dificultad = "Intermedio",
                            GrupoMuscular = "Hombros",
                            Nombre = "Press Militar"
                        },
                        new
                        {
                            EjercicioId = 6,
                            Descripcion = "Ejercicio compuesto para espalda baja y pierna",
                            Dificultad = "Avanzado",
                            GrupoMuscular = "Espalda",
                            Nombre = "Peso Muerto"
                        },
                        new
                        {
                            EjercicioId = 7,
                            Descripcion = "Ejercicio para tríceps y pecho",
                            Dificultad = "Intermedio",
                            GrupoMuscular = "Pecho",
                            Nombre = "Fondos en Paralelas"
                        },
                        new
                        {
                            EjercicioId = 8,
                            Descripcion = "Ejercicio isométrico para core",
                            Dificultad = "Básico",
                            GrupoMuscular = "Core",
                            Nombre = "Plancha"
                        });
                });

            modelBuilder.Entity("GymTrack.Models.Rutina", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutinaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("RutinaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("GymTrack.Models.RutinaEjercicio", b =>
                {
                    b.Property<int>("RutinaEjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutinaEjercicioId"));

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int>("RutinaId")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("RutinaEjercicioId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("GymTrack.Models.Sesion", b =>
                {
                    b.Property<int>("SesionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SesionId"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("RutinaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SesionId");

                    b.HasIndex("RutinaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("GymTrack.Models.SesionDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RepsHechas")
                        .HasColumnType("int");

                    b.Property<int>("SeriesHechas")
                        .HasColumnType("int");

                    b.Property<int>("SesionId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("SesionId");

                    b.ToTable("SesionDetalles");
                });

            modelBuilder.Entity("GymTrack.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GymTrack.Models.Rutina", b =>
                {
                    b.HasOne("GymTrack.Models.Usuario", null)
                        .WithMany("Rutinas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTrack.Models.RutinaEjercicio", b =>
                {
                    b.HasOne("GymTrack.Models.Ejercicio", "Ejercicio")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrack.Models.Rutina", "Rutina")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("GymTrack.Models.Sesion", b =>
                {
                    b.HasOne("GymTrack.Models.Rutina", "Rutina")
                        .WithMany()
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrack.Models.Usuario", null)
                        .WithMany("Sesiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("GymTrack.Models.SesionDetalle", b =>
                {
                    b.HasOne("GymTrack.Models.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymTrack.Models.Sesion", "Sesion")
                        .WithMany("Detalles")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("GymTrack.Models.Ejercicio", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("GymTrack.Models.Rutina", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("GymTrack.Models.Sesion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("GymTrack.Models.Usuario", b =>
                {
                    b.Navigation("Rutinas");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
